name: Docker

on:
  push:
    # Publish `main` as `latest` image.
    branches:
      - main

  # Run builds for any PRs.
  pull_request:
    
  workflow_dispatch:

env:
  IMAGE_NAME: haskpod

jobs:
  # Test image build.
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: podman build . 

  # Push image to GitHub Container Registry.
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: podman build -t hasktorch . 

      - name: Push image
        run: podman push --creds $REGISTRY_USERNAME:$REGISTRY_TOKEN haskpod ghcr.io/$REGISTRY_USERNAME/haskpod:latest
